// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

type Chat struct {
	ChatID                      int64
	EncryptedPrivateIdentityKey []byte
	EncryptedTitle              []byte
	EncryptedDescription        []byte
}

type Message struct {
	ChatID                     int64
	SequenceNumber             int64
	EncryptedPublicIdentityKey []byte
	EncryptedContent           []byte
	EncryptedCreatedAt         []byte
}

type Participant struct {
	ChatID                     int64
	SequenceNumber             int64
	EncryptedPublicIdentityKey []byte
	EncryptedName              []byte
	EncryptedEcdhPublicKey     []byte
	EncryptedMyEcdhPrivateKey  []byte
}

type Password struct {
	ID   int64
	Salt []byte
}
